# Generated by Django 2.2.7 on 2019-11-14 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=300, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=300, null=True)),
                ('DNI', models.CharField(blank=True, max_length=300, null=True)),
                ('historia', models.CharField(blank=True, max_length=300, null=True)),
                ('imagen', models.CharField(blank=True, max_length=300, null=True)),
                ('doctor', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
